/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_tanushree_spellathon_MyNDK */

#ifndef _Included_com_example_tanushree_spellathon_MyNDK
#define _Included_com_example_tanushree_spellathon_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_tanushree_spellathon_MyNDK
 * Method:    getMyString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_tanushree_spellathon_MyNDK_getMyString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_tanushree_spellathon_MyNDK
 * Method:    dictionary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_tanushree_spellathon_MyNDK_dictionary
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
